#!/bin/sh
#
# Very simple session manager for Mini X
#

# Uncomment below to enable parsing of debian menu entrys
# export MB_USE_DEB_MENUS=1 

if [ -e $HOME/.mini_x/session ]
then
exec $HOME/.mini_x/session
fi

if [ -e /etc/mini_x/session ]
then
exec /etc/mini_x/session
fi

MINI_X_SESSION_DIR=/etc/mini_x/session.d
if [ -d "$MINI_X_SESSION_DIR" ]; then
        # Execute session file on behalf of file owner
        find $MINI_X_SESSION_DIR -type f | while read SESSIONFILE; do
                set +e
                USERNAME=`stat -c %U $SESSIONFILE`
                # Using su rather than sudo as latest 1.8.1 cause failure [YOCTO #1211]
#               su -l -c '$SESSIONFILE&' $USERNAME
                sudo -b -i -u $USERNAME $SESSIONFILE&
                set -e
        done
fi

xrandr -s 1600x900

export DISPLAY=:0
xset s off
xset -dpms
xset s noblank

sleep 10                   

su - kiosk -c '
  dbus-run-session -- env DISPLAY=:0 WEBKIT_DISABLE_DMABUF_RENDERER=1 \
    epiphany --application-mode --incognito-mode \
             --profile="$HOME/.local/share/org.gnome.Epiphany.WebApp-kiosk" \
             localhost
' &

sleep 10

xdotool key "F11" &

exec matchbox-window-manager
